### ISSUE TITLE
Clarify support for SVM DR

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud-manager-fsx-ontap#11]
Page: [Manage volumes for Amazon FSx for ONTAP](https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-manage-fsx-volumes.html)

On this page replicating data using FSx is mentioned.  Can this be expanded to clarify if only volume level SnapMirror is supported within FSx, or if SVM level SnapMirror (SVM DR) is also supported by FSx?

**Comment by juliantap** [comment]
@mimitche, thanks for the feedback! At this time, SnapMirror replication from FSx is supported using CLI only. I've updated the limitations page to reflect this. This issue will auto-close when the change merges, but you can still reply to me in this thread. Thanks!

**Comment by mimitche** [comment]
Thanks!  Just to be sure- this means both SnapMirror for volumes and
SnapMirror for SVMs (aka SVM DR) is supported from the ONTAP command line?

**Comment by juliantap** [comment]
@mimitche, I'm verifying this. I'll update here as soon as I have confirmation.

**Comment by juliantap** [comment]
@mimitche, I believe you've gotten the answer now :-) Let me know if you need anything else.
