### ISSUE TITLE
The text in the screenshots is too small to read.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloud-manager-fsx-ontap#16]
Page: [Security group rules for FSx for ONTAP](https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/requirements/reference-security-groups-fsx.html)

The text in the screenshots is too small to read.
If you can't read the text, it doesn't make sense to paste the screen shot.
Please paste the enlarged one.

**Comment by juliantap** [comment]
Hi @kanitani, please check out the updates to the screenshots and see if that helps. If not, let me know. 

Thank you for contributing to the quality of our documentation!

**Comment by kanitani** [comment]
OK. Thanks!
