### ISSUE TITLE
Request for updating Limitation info of how we setup snapmirror relationship for FSx ONTAP

### ISSUE THREAD

**Issue by naotocurry** [NetAppDocs/cloud-manager-fsx-ontap#31]
Page: [Learn about Amazon FSx for ONTAP](https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/concept-fsx-aws.html)

Could you please update Limitations information regarding supported method of snapmirror setting? According to URL below, all the combination and direction of snapmirror relationship can be done by using cloud manager at this point.
https://docs.netapp.com/us-en/cloud-manager-replication/whats-new.html#18-sept-2022

**Comment by juliantap** [comment]
Hi @naotocurry, thank you for your feedback. I'm verifying with engineering that the limitations can now be removed.

**Comment by juliantap** [comment]
Hi @naotocurry, sorry for the delay! The document has been updated to remove the limitations. Thank you for contributing the quality of our documentation! This issue will auto-close when the change is merged. If you have any additional comments you can continue to comment on this issue.
