### ISSUE TITLE
add required permissions

### ISSUE THREAD

**Issue by guypar** [NetAppDocs/cloud-manager-fsx-ontap#36]
Page: [Set up permissions for FSx for ONTAP](https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/requirements/task-setting-up-permissions-fsx.html)
need to add :
   "cloudwatch:GetMetricData",
   "cloudwatch:GetMetricStatistics"
to the list of required permissions

**Comment by juliantap** [comment]
@guypar thank you for checking on this. The new permissions were added along with #38.
