### ISSUE TITLE
Wrong Details panel screenshot and configuration procedure 

### ISSUE THREAD

**Issue by buslovitch** [NetAppDocs/cloud-manager-fsx-ontap#47]
Page: [Manage an Amazon FSx for NetApp ONTAP working environment](https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-manage-working-environment.html)

A menu that enables Automatic Capacity Management moved here:
![image](https://user-images.githubusercontent.com/122797022/232472684-fe7f9cb8-1d08-4ea0-936f-734b864f95ef.png)

**Comment by juliantap** [comment]
Hi @buslovitch, thank you for the feedback. The process for updating Auto capacity management varies based on whether you have an active Connector or don't. However, the documented process was still incorrect and I've updated it. This issue will auto-close when the change is merged but you can continue to comment on it and I will be notified. 

Thank you for contributing to the quality of the documentation!
