### ISSUE TITLE
Account ID listed for FsX IAM role is incorrect for GovCloud 

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud-manager-fsx-ontap#9]
Page: [Set up permissions for FSx for ONTAP](https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/requirements/task-setting-up-permissions-fsx.html)

The account ID listed on this documentation (952013314444) does not work when setting up an IAM role for FSX in AWS GovCloud.  It returns an "invalid principal" error.  I suspect the account ID used for FsX in GovCloud is different and needs to be documented on this page.

**Comment by juliantap** [comment]
Hi @mimitche, thank you for the feedback. I'll check with engineering to see if there is a different account ID required.

**Comment by juliantap** [comment]
@mimitche, can you confirm that you are using the local version of Cloud Manager for this deployment? 

The engineering team is evaluating the issue. Because GovCloud cannot connect to our SaaS version (due to compliance), AWS role assumption should be disallowed.

**Comment by juliantap** [comment]
Perfect, thanks! This is what they needed to know. We'll get that fixed and I'll update the docs when it's complete.

**Comment by juliantap** [comment]
#20 fixes this 

Thanks again, @mimitche!

**Comment by juliantap** [comment]
This issue was resolved on Jul 3 but did not auto-close. Closing it now.
